services:
  frontend:
    image: nginx:stable-alpine
    # ports:
    #   - 3000:80
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
  backend:
    build: backend
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - backend_files:/tmp
      - ./backend/src:/app/src
    ports:
      - 11432:5000
    # depends_on:
    #   - db
    #   - ollama
  # db:
  #   image: postgres:13
  #   env_file:
  #     - .env
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  proxy:
    image: nginx:1.13-alpine
    ports:
      - 3000:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - 11434:11434
  #   env_file:
  #     - .env
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [ gpu ]
  # volumes:
  #   - ollama_models:/root/.ollama

volumes:
  postgres_data:
  backend_files:
  ollama_models:
