version: "3.8"

services:
  web:
    image: nginx:stable-alpine
    ports:
      - 3000:80
    volumes:
      - ./web:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/nginx.conf
  python_proxy:
    build: python_proxy
    ports:
      - 11433:5000
    env_file:
      - .env
    volumes:
      - ./python_proxy/model_mapping.json:/app/model_mapping.json
      - ./saved_chats:/app/saved_chats
      - ./tmp:/tmp
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
